apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact
  namespace: k8s-3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contact
  template:
    metadata:
      labels:
        app: contact
    spec:
      containers:
      - name: contact
        image: 861531569385.dkr.ecr.us-west-1.amazonaws.com/sparkjava:6
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
